-- lua/lumaxs/palettes/immersive-emerald.lua
-- generated by lumaxs-gen

return {
	-- Required
	bg = "#080E14",
	fg = "#aaaaaa",
	keyword = "#1ae824",
	func = "#1ae8ae",
	type_ = "#168991", -- underscore: "type" is a reserved keyword in Lua!
	string = "#52eec2",
	number = "#15cf1e",
	comment = "#545454",
	operator = "#127076",

	-- Backgrounds
	surface = "#1c1c1c",
	line = "#2c2c2c",
	selection = "#4a4a4a",
	border = "#1c1c1c",
	border_focus = "#15d31e",
	bg_dark = "#000000",
	bg_hover = "#2c2c2c",
	bg_active = "#4a4a4a",
	float_bg = "#1c1c1c",
	float_border = "#15d31e",

	-- Foregrounds
	fg_muted = "#515151",
	fg_subtle = "#323232",
	fg_disabled = "#262626",
	line_nr = "#282828",
	line_nr_active = "#1ae824",

	-- Semantic
	ok = "#4ec994",
	error = "#cc5555",
	warn = "#1ae8ad",
	info = "#77e81a",
	hint = "#33cf3b",
	git_mod = "#1ae8ad",

	-- Diff fg
	diff_add = "#4ec994",
	diff_del = "#cc5555",
	diff_chg = "#77e81a",

	-- Diff bg
	diff_add_bg = "#21372d",
	diff_del_bg = "#372121",
	diff_chg_bg = "#2b3721",

	-- Virtual text bg
	vt_err = "#372121",
	vt_warn = "#2b3721",
	vt_info = "#21372d",
	vt_hint = "#1c1c1c",
}
