-- lua/lumaxs/palettes/void.lua
-- generated by lumaxs-gen

return {
  -- Required
  bg       = "#070a0f",
  fg       = "#9ba7c1",
  keyword  = "#00b4d8",
  func     = "#12b9db",
  type_    = "#0aa5c4",   -- underscore: "type" is a reserved keyword in Lua!
  string   = "#0048d8",
  number   = "#2400d8",
  comment  = "#262d3d",
  operator = "#313b50",

  -- Backgrounds
  surface      = "#0a0f16",
  line         = "#0d131d",
  selection    = "#141d2b",
  border       = "#0a0f16",
  border_focus = "#009fbf",
  bg_dark      = "#040508",
  bg_hover     = "#0d131d",
  bg_active    = "#141d2b",
  float_bg     = "#0a0f16",
  float_border = "#009fbf",

  -- Foregrounds
  fg_muted       = "#414e69",
  fg_subtle      = "#2a3243",
  fg_disabled    = "#202633",
  line_nr        = "#222837",
  line_nr_active = "#00b4d8",

  -- Semantic
  ok      = "#4ec994",
  error   = "#cc5555",
  warn    = "#0024d8",
  info    = "#00d890",
  hint    = "#16a6c2",
  git_mod = "#0024d8",

  -- Diff fg
  diff_add = "#4ec994",
  diff_del = "#cc5555",
  diff_chg = "#00d890",

  -- Diff bg
  diff_add_bg = "#101a16",
  diff_del_bg = "#1a1010",
  diff_chg_bg = "#101a17",

  -- Virtual text bg
  vt_err  = "#1a1010",
  vt_warn = "#101a17",
  vt_info = "#101a16",
  vt_hint = "#0a0f16",
}
