--[[
    All highlight groups — a single copy shared across all themes.
    Receives the normalized palette via M.apply(c).
]]

local M = {}

function M.apply(c)
    local function hi(group, opts)
        vim.api.nvim_set_hl(0, group, opts)
    end

    -- [[ EDITOR UI ]] --

    hi("Normal", { fg = c.fg, bg = c.bg })
    hi("NormalFloat", { fg = c.fg, bg = c.float_bg })
    hi("NormalNC", { fg = c.fg_muted, bg = c.bg })
    hi("NormalSB", { fg = c.fg, bg = c.surface })
    hi("FloatBorder", { fg = c.float_border, bg = c.float_bg })
    hi("FloatTitle", { fg = c.accent, bg = c.float_bg, bold = true })
    hi("FloatFooter", { fg = c.fg_muted, bg = c.float_bg })
    hi("FloatShadow", { bg = c.bg })
    hi("FloatShadowThrough", { bg = c.bg })

    hi("SignColumn", { fg = c.line_nr, bg = c.bg })
    hi("FoldColumn", { fg = c.fg_subtle, bg = c.bg })
    hi("ColorColumn", { bg = c.line })
    hi("CursorLine", { bg = c.line })
    hi("CursorColumn", { bg = c.line })
    hi("CursorLineNr", { fg = c.line_nr_active, bg = c.line, bold = true })
    hi("LineNr", { fg = c.line_nr })
    hi("LineNrAbove", { fg = c.line_nr })
    hi("LineNrBelow", { fg = c.line_nr })
    hi("CursorLineFold", { fg = c.fg_subtle, bg = c.line })
    hi("CursorLineSign", { fg = c.line_nr, bg = c.line })

    hi("Cursor", { fg = c.bg, bg = c.accent })
    hi("CursorIM", { fg = c.bg, bg = c.accent })
    hi("TermCursor", { fg = c.bg, bg = c.fg })
    hi("TermCursorNC", { fg = c.bg, bg = c.line_nr })
    hi("lCursor", { fg = c.bg, bg = c.fg })

    -- [[ SELECTION & SEARCH ]] --

    hi("Visual", { bg = c.bg_active })
    hi("VisualNOS", { bg = c.bg_active })
    hi("Search", { fg = c.bg, bg = c.accent })
    hi("IncSearch", { fg = c.bg, bg = c.keyword, bold = true })
    hi("CurSearch", { fg = c.bg, bg = c.keyword, bold = true })
    hi("Substitute", { fg = c.bg, bg = c.type_ })
    hi("QuickFixLine", { bg = c.bg_active })

    -- [[ WINDOWS, SPLITS, STATUSLINE ]] --

    hi("WinSeparator", { fg = c.border, bg = c.bg })
    hi("VertSplit", { fg = c.border, bg = c.bg })

    hi("StatusLine", { fg = c.fg, bg = c.bg_dark })
    hi("StatusLineNC", { fg = c.fg_muted, bg = c.bg_dark })
    hi("StatusLineTerm", { fg = c.fg, bg = c.bg_dark })
    hi("StatusLineTermNC", { fg = c.fg_muted, bg = c.bg_dark })

    hi("TabLine", { fg = c.fg_muted, bg = c.bg_dark })
    hi("TabLineSel", { fg = c.fg, bg = c.bg, bold = true })
    hi("TabLineFill", { bg = c.bg_dark })

    hi("WinBar", { fg = c.fg, bg = c.bg })
    hi("WinBarNC", { fg = c.fg_muted, bg = c.bg })

    -- [[ POPUP MENU ]] --

    hi("Pmenu", { fg = c.fg, bg = c.float_bg })
    hi("PmenuSel", { fg = c.fg, bg = c.bg_active, bold = true })
    hi("PmenuSbar", { bg = c.bg_dark })
    hi("PmenuThumb", { bg = c.border_focus })
    hi("PmenuMatch", { fg = c.string, bold = true })
    hi("PmenuMatchSel", { fg = c.string, bg = c.bg_active, bold = true })
    hi("PmenuKind", { fg = c.accent, bg = c.float_bg })
    hi("PmenuKindSel", { fg = c.accent, bg = c.bg_active })
    hi("PmenuExtra", { fg = c.fg_muted, bg = c.float_bg })
    hi("PmenuExtraSel", { fg = c.fg_muted, bg = c.bg_active })

    -- [[ MISC UI ]] --

    hi("Folded", { fg = c.fg_muted, bg = c.bg_active, italic = true })
    hi("Conceal", { fg = c.fg_muted })
    hi("NonText", { fg = c.fg_disabled })
    hi("SpecialKey", { fg = c.fg_subtle })
    hi("Whitespace", { fg = c.fg_disabled })
    hi("EndOfBuffer", { fg = c.bg })
    hi("MatchParen", { fg = c.accent, bg = c.bg_active, bold = true, underline = true })
    hi("Title", { fg = c.accent, bold = true })
    hi("Directory", { fg = c.func })

    hi("ModeMsg", { fg = c.fg, bold = true })
    hi("MsgArea", { fg = c.fg })
    hi("MsgSeparator", { fg = c.border })
    hi("MoreMsg", { fg = c.ok })
    hi("Question", { fg = c.info })
    hi("ErrorMsg", { fg = c.error })
    hi("WarningMsg", { fg = c.warn })

    hi("SpellBad", { sp = c.error, undercurl = true })
    hi("SpellCap", { sp = c.warn, undercurl = true })
    hi("SpellLocal", { sp = c.info, undercurl = true })
    hi("SpellRare", { sp = c.hint, undercurl = true })

    hi("Winsbar", { fg = c.fg_muted, bg = c.surface })

    -- [[ DIFF ]] --

    hi("DiffAdd", { fg = c.diff_add, bg = c.diff_add_bg })
    hi("DiffChange", { fg = c.diff_chg, bg = c.diff_chg_bg })
    hi("DiffDelete", { fg = c.diff_del, bg = c.diff_del_bg })
    hi("DiffText", { fg = c.fg, bg = c.diff_chg_bg, bold = true })
    hi("Added", { fg = c.diff_add })
    hi("Removed", { fg = c.diff_del })
    hi("Changed", { fg = c.diff_chg })

    -- [[ DIAGNOSTICS ]] --

    hi("DiagnosticError", { fg = c.error })
    hi("DiagnosticWarn", { fg = c.warn })
    hi("DiagnosticInfo", { fg = c.info })
    hi("DiagnosticHint", { fg = c.hint })
    hi("DiagnosticOk", { fg = c.ok })
    hi("DiagnosticUnnecessary", { fg = c.fg_muted })
    hi("DiagnosticDeprecated", { fg = c.fg_muted, strikethrough = true })

    hi("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
    hi("DiagnosticUnderlineWarn", { sp = c.warn, undercurl = true })
    hi("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
    hi("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
    hi("DiagnosticUnderlineOk", { sp = c.ok, underline = true })

    hi("DiagnosticVirtualTextError", { fg = c.error, bg = c.vt_err, italic = true })
    hi("DiagnosticVirtualTextWarn", { fg = c.warn, bg = c.vt_warn, italic = true })
    hi("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.vt_info, italic = true })
    hi("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.vt_hint, italic = true })
    hi("DiagnosticVirtualTextOk", { fg = c.ok, bg = c.bg, italic = true })

    hi("DiagnosticSignError", { fg = c.error })
    hi("DiagnosticSignWarn", { fg = c.warn })
    hi("DiagnosticSignInfo", { fg = c.info })
    hi("DiagnosticSignHint", { fg = c.hint })
    hi("DiagnosticSignOk", { fg = c.ok })

    hi("DiagnosticFloatingError", { fg = c.error, bg = c.float_bg })
    hi("DiagnosticFloatingWarn", { fg = c.warn, bg = c.float_bg })
    hi("DiagnosticFloatingInfo", { fg = c.info, bg = c.float_bg })
    hi("DiagnosticFloatingHint", { fg = c.hint, bg = c.float_bg })
    hi("DiagnosticFloatingOk", { fg = c.ok, bg = c.float_bg })

    -- [[ LSP ]] --

    hi("LspReferenceText", { bg = c.line })
    hi("LspReferenceRead", { bg = c.vt_info })
    hi("LspReferenceWrite", { bg = c.bg_active })
    hi("LspInlayHint", { fg = c.hint, bg = c.float_bg, italic = true })
    hi("LspCodeLens", { fg = c.hint, italic = true })
    hi("LspCodeLensSeparator", { fg = c.border_focus })
    hi("LspSignatureActiveParameter", { fg = c.warn, bold = true })
    hi("LspInfoBorder", { fg = c.float_border, bg = c.float_bg })
    hi("LspInfoFiletype", { fg = c.type_ })
    hi("LspInfoTip", { fg = c.fg_muted, italic = true })
    hi("LspInfoTitle", { fg = c.accent, bold = true })
    hi("LspInfoList", { fg = c.fg })

    -- [[ CLASSIC SYNTAX (vim) ]] --

    hi("Comment", { fg = c.comment, italic = true })
    hi("SpecialComment", { fg = c.comment, bold = true })
    hi("Constant", { fg = c.constant })
    hi("String", { fg = c.string })
    hi("Character", { fg = c.string })
    hi("Number", { fg = c.number })
    hi("Boolean", { fg = c.number })
    hi("Float", { fg = c.number })
    hi("Identifier", { fg = c.fg })
    hi("Function", { fg = c.func })
    hi("Statement", { fg = c.keyword })
    hi("Conditional", { fg = c.keyword })
    hi("Repeat", { fg = c.keyword })
    hi("Label", { fg = c.accent })
    hi("Operator", { fg = c.operator })
    hi("Keyword", { fg = c.keyword })
    hi("Exception", { fg = c.keyword })
    hi("PreProc", { fg = c.keyword })
    hi("Include", { fg = c.keyword })
    hi("Define", { fg = c.keyword })
    hi("Macro", { fg = c.type_ })
    hi("PreCondit", { fg = c.keyword })
    hi("Type", { fg = c.type_ })
    hi("StorageClass", { fg = c.keyword })
    hi("Structure", { fg = c.type_ })
    hi("Typedef", { fg = c.type_ })
    hi("Special", { fg = c.accent })
    hi("SpecialChar", { fg = c.string_spec })
    hi("Tag", { fg = c.keyword })
    hi("Delimiter", { fg = c.punct })
    hi("Debug", { fg = c.warn })
    hi("Underlined", { fg = c.accent, underline = true })
    hi("Ignore", { fg = c.fg_disabled })
    hi("Error", { fg = c.error })
    hi("Todo", { fg = c.bg, bg = c.keyword, bold = true })

    -- [[ TREESITTER ]] --

    -- comments
    hi("@comment", { fg = c.comment, italic = true })
    hi("@comment.documentation", { fg = c.comment_doc, bold = true, italic = true })
    hi("@comment.error", { fg = c.error, italic = true })
    hi("@comment.warning", { fg = c.warn, italic = true })
    hi("@comment.note", { fg = c.info, italic = true })
    hi("@comment.todo", { fg = c.bg, bg = c.keyword, bold = true })

    -- keywords
    hi("@keyword", { fg = c.keyword })
    hi("@keyword.function", { fg = c.keyword })
    hi("@keyword.operator", { fg = c.operator })
    hi("@keyword.return", { fg = c.keyword })
    hi("@keyword.import", { fg = c.keyword })
    hi("@keyword.conditional", { fg = c.keyword })
    hi("@keyword.conditional.ternary", { fg = c.operator })
    hi("@keyword.repeat", { fg = c.keyword })
    hi("@keyword.exception", { fg = c.keyword })
    hi("@keyword.modifier", { fg = c.keyword })
    hi("@keyword.coroutine", { fg = c.keyword })
    hi("@keyword.type", { fg = c.keyword })
    hi("@keyword.debug", { fg = c.warn })
    hi("@keyword.directive", { fg = c.type_ })
    hi("@keyword.directive.define", { fg = c.keyword })
    hi("@keyword.storage", { fg = c.keyword })
    hi("@keyword.export", { fg = c.keyword })

    -- functions
    hi("@function", { fg = c.func })
    hi("@function.builtin", { fg = c.func, italic = true })
    hi("@function.call", { fg = c.func })
    hi("@function.macro", { fg = c.type_ })
    hi("@function.method", { fg = c.func })
    hi("@function.method.call", { fg = c.func })
    hi("@constructor", { fg = c.type_ })

    -- variables
    hi("@variable", { fg = c.fg })
    hi("@variable.builtin", { fg = c.keyword, italic = true })
    hi("@variable.member", { fg = c.property })
    hi("@variable.parameter", { fg = c.number })
    hi("@variable.parameter.builtin", { fg = c.number, italic = true })

    -- tipos
    hi("@type", { fg = c.type_ })
    hi("@type.builtin", { fg = c.type_, italic = true })
    hi("@type.definition", { fg = c.type_ })
    hi("@type.qualifier", { fg = c.keyword })

    -- literais
    hi("@string", { fg = c.string })
    hi("@string.escape", { fg = c.string_esc })
    hi("@string.special", { fg = c.string_spec })
    hi("@string.special.symbol", { fg = c.string })
    hi("@string.special.url", { fg = c.string_re, underline = true })
    hi("@string.special.path", { fg = c.string_re })
    hi("@string.regexp", { fg = c.string_re })
    hi("@string.documentation", { fg = c.string, italic = true })
    hi("@number", { fg = c.number })
    hi("@number.float", { fg = c.number })
    hi("@boolean", { fg = c.number })
    hi("@character", { fg = c.string })
    hi("@character.special", { fg = c.string_spec })

    -- constantes
    hi("@constant", { fg = c.constant })
    hi("@constant.builtin", { fg = c.keyword, italic = true })
    hi("@constant.macro", { fg = c.type_ })

    -- operators & punctuation
    hi("@operator", { fg = c.operator })
    hi("@punctuation", { fg = c.punct })
    hi("@punctuation.bracket", { fg = c.punct })
    hi("@punctuation.delimiter", { fg = c.punct })
    hi("@punctuation.special", { fg = c.string_spec })

    -- modules
    hi("@module", { fg = c.namespace })
    hi("@module.builtin", { fg = c.namespace, italic = true })
    hi("@namespace", { fg = c.namespace })
    hi("@label", { fg = c.accent })

    -- atributos & propriedades
    hi("@attribute", { fg = c.accent })
    hi("@attribute.builtin", { fg = c.accent, italic = true })
    hi("@property", { fg = c.property })
    hi("@field", { fg = c.property })
    hi("@parameter", { fg = c.number })
    hi("@annotation", { fg = c.type_ })

    -- markup
    hi("@markup.heading", { fg = c.accent, bold = true })
    hi("@markup.heading.1", { fg = c.keyword, bold = true })
    hi("@markup.heading.2", { fg = c.type_, bold = true })
    hi("@markup.heading.3", { fg = c.func, bold = true })
    hi("@markup.heading.4", { fg = c.string, bold = true })
    hi("@markup.heading.5", { fg = c.number, bold = true })
    hi("@markup.heading.6", { fg = c.operator, bold = true })
    hi("@markup.italic", { italic = true })
    hi("@markup.strong", { bold = true })
    hi("@markup.bold", { bold = true })
    hi("@markup.strikethrough", { strikethrough = true })
    hi("@markup.underline", { underline = true })
    hi("@markup.link", { fg = c.func, underline = true })
    hi("@markup.link.label", { fg = c.func })
    hi("@markup.link.url", { fg = c.string_re, underline = true })
    hi("@markup.raw", { fg = c.string })
    hi("@markup.raw.block", { fg = c.string, bg = c.surface })
    hi("@markup.list", { fg = c.punct })
    hi("@markup.list.checked", { fg = c.ok })
    hi("@markup.list.unchecked", { fg = c.fg_muted })
    hi("@markup.quote", { fg = c.comment, italic = true })
    hi("@markup.math", { fg = c.number })
    hi("@markup.environment", { fg = c.keyword })
    hi("@markup.environment.name", { fg = c.type_ })

    -- diff
    hi("@diff.plus", { fg = c.diff_add })
    hi("@diff.minus", { fg = c.diff_del })
    hi("@diff.delta", { fg = c.diff_chg })

    -- tags
    hi("@tag", { fg = c.keyword })
    hi("@tag.builtin", { fg = c.keyword, italic = true })
    hi("@tag.attribute", { fg = c.accent })
    hi("@tag.delimiter", { fg = c.punct })

    -- misc
    hi("@none", {})
    hi("@conceal", { fg = c.fg_disabled })
    hi("@error", { fg = c.error })

    -- compat legado
    hi("@text.strong", { bold = true })
    hi("@text.emphasis", { italic = true })
    hi("@text.underline", { underline = true })
    hi("@text.strike", { strikethrough = true })
    hi("@text.title", { fg = c.accent, bold = true })
    hi("@text.uri", { fg = c.string_re, underline = true })
    hi("@text.reference", { fg = c.func })
    hi("@text.todo", { fg = c.bg, bg = c.keyword })
    hi("@text.note", { fg = c.info })
    hi("@text.warning", { fg = c.warn })
    hi("@text.danger", { fg = c.error })

    -- [[ LSP SEMANTIC TOKENS ]] --

    hi("@lsp.type.class", { fg = c.type_ })
    hi("@lsp.type.comment", { link = "Comment" })
    hi("@lsp.type.decorator", { fg = c.func })
    hi("@lsp.type.enum", { fg = c.constant })
    hi("@lsp.type.enumMember", { fg = c.constant })
    hi("@lsp.type.event", { fg = c.property })
    hi("@lsp.type.function", { fg = c.func })
    hi("@lsp.type.interface", { fg = c.type_ })
    hi("@lsp.type.keyword", { fg = c.keyword })
    hi("@lsp.type.macro", { fg = c.type_ })
    hi("@lsp.type.method", { fg = c.func })
    hi("@lsp.type.modifier", { fg = c.keyword })
    hi("@lsp.type.namespace", { fg = c.namespace })
    hi("@lsp.type.number", { fg = c.number })
    hi("@lsp.type.operator", { fg = c.operator })
    hi("@lsp.type.parameter", { fg = c.number })
    hi("@lsp.type.property", { fg = c.property })
    hi("@lsp.type.regexp", { fg = c.string_re })
    hi("@lsp.type.string", { fg = c.string })
    hi("@lsp.type.struct", { fg = c.type_ })
    hi("@lsp.type.type", { fg = c.type_ })
    hi("@lsp.type.typeParameter", { fg = c.type_ })
    hi("@lsp.type.variable", { fg = c.fg })
    hi("@lsp.type.builtinType", { fg = c.type_, italic = true })
    hi("@lsp.type.lifetime", { fg = c.keyword, italic = true })
    hi("@lsp.type.selfKeyword", { fg = c.keyword, italic = true })
    hi("@lsp.type.selfTypeKeyword", { fg = c.type_, italic = true })
    hi("@lsp.type.escapeSequence", { fg = c.string_esc })
    hi("@lsp.type.formatSpecifier", { fg = c.string_spec })
    hi("@lsp.type.generic", { fg = c.type_ })
    hi("@lsp.type.label", { fg = c.accent })
    hi("@lsp.mod.deprecated", { strikethrough = true })
    hi("@lsp.mod.readonly", { fg = c.constant })
    hi("@lsp.mod.static", { italic = true })
    hi("@lsp.mod.abstract", { italic = true })
    hi("@lsp.mod.async", { fg = c.keyword, italic = true })
    hi("@lsp.mod.defaultLibrary", { italic = true })
    hi("@lsp.mod.documentation", { fg = c.comment_doc })
    hi("@lsp.mod.injected", {})
    hi("@lsp.mod.library", { italic = true })
    hi("@lsp.mod.public", {})

    -- [[ TELESCOPE ]] --

    hi("TelescopeBorder", { fg = c.float_border, bg = c.float_bg })
    hi("TelescopeNormal", { fg = c.fg, bg = c.float_bg })
    hi("TelescopePromptBorder", { fg = c.border_focus, bg = c.bg_dark })
    hi("TelescopePromptNormal", { fg = c.fg, bg = c.bg_dark })
    hi("TelescopePromptPrefix", { fg = c.accent })
    hi("TelescopePromptCounter", { fg = c.fg_muted })
    hi("TelescopePromptTitle", { fg = c.accent, bold = true })
    hi("TelescopeResultsBorder", { fg = c.border, bg = c.float_bg })
    hi("TelescopeResultsNormal", { fg = c.fg, bg = c.float_bg })
    hi("TelescopeResultsTitle", { fg = c.fg_muted })
    hi("TelescopePreviewBorder", { fg = c.border, bg = c.float_bg })
    hi("TelescopePreviewNormal", { fg = c.fg, bg = c.float_bg })
    hi("TelescopePreviewTitle", { fg = c.func, bold = true })
    hi("TelescopeSelection", { fg = c.fg, bg = c.bg_active })
    hi("TelescopeSelectionCaret", { fg = c.accent, bg = c.bg_active })
    hi("TelescopeMultiSelection", { fg = c.type_, bg = c.bg_active })
    hi("TelescopeMatching", { fg = c.accent, bold = true })
    hi("TelescopeTitle", { fg = c.accent, bold = true })
    hi("TelescopeResultsDiffAdd", { fg = c.diff_add })
    hi("TelescopeResultsDiffChange", { fg = c.diff_chg })
    hi("TelescopeResultsDiffDelete", { fg = c.diff_del })
    hi("TelescopeResultsDiffUntracked", { fg = c.fg_muted })

    -- [[ FZF-LUA ]] --

    hi("FzfLuaNormal", { fg = c.fg, bg = c.float_bg })
    hi("FzfLuaBorder", { fg = c.float_border, bg = c.float_bg })
    hi("FzfLuaTitle", { fg = c.accent, bold = true })
    hi("FzfLuaPreviewNormal", { fg = c.fg, bg = c.float_bg })
    hi("FzfLuaPreviewBorder", { fg = c.border, bg = c.float_bg })
    hi("FzfLuaPreviewTitle", { fg = c.func, bold = true })
    hi("FzfLuaCursor", { fg = c.bg, bg = c.accent })
    hi("FzfLuaSearch", { fg = c.accent, bold = true })
    hi("FzfLuaSel", { fg = c.fg, bg = c.bg_active })
    hi("FzfLuaSelBorderText", { fg = c.border_focus, bold = true })
    hi("FzfLuaHeaderBind", { fg = c.func })
    hi("FzfLuaHeaderText", { fg = c.fg_muted })

    -- [[ NVIM-TREE ]] --

    hi("NvimTreeNormal", { fg = c.fg, bg = c.surface })
    hi("NvimTreeNormalNC", { fg = c.fg_muted, bg = c.surface })
    hi("NvimTreeRootFolder", { fg = c.accent, bold = true })
    hi("NvimTreeFolderName", { fg = c.func })
    hi("NvimTreeFolderIcon", { fg = c.info })
    hi("NvimTreeFileIcon", { fg = c.fg_muted })
    hi("NvimTreeOpenedFolderName", { fg = c.keyword })
    hi("NvimTreeEmptyFolderName", { fg = c.fg_muted })
    hi("NvimTreeFileName", { fg = c.fg })
    hi("NvimTreeSpecialFile", { fg = c.string })
    hi("NvimTreeImageFile", { fg = c.number })
    hi("NvimTreeExecFile", { fg = c.ok, bold = true })
    hi("NvimTreeSymlink", { fg = c.type_ })
    hi("NvimTreeSymlinkArrow", { fg = c.operator })
    hi("NvimTreeGitDirty", { fg = c.warn })
    hi("NvimTreeGitNew", { fg = c.ok })
    hi("NvimTreeGitDeleted", { fg = c.error })
    hi("NvimTreeGitStaged", { fg = c.ok })
    hi("NvimTreeGitMerge", { fg = c.type_ })
    hi("NvimTreeGitRenamed", { fg = c.type_ })
    hi("NvimTreeIndentMarker", { fg = c.border })
    hi("NvimTreeWinSeparator", { fg = c.border, bg = c.surface })
    hi("NvimTreeCursorLine", { bg = c.bg_active })
    hi("NvimTreeEndOfBuffer", { fg = c.surface })
    hi("NvimTreeStatusLine", { fg = c.surface, bg = c.surface })
    hi("NvimTreeStatusLineNC", { fg = c.surface, bg = c.surface })
    hi("NvimTreeBookmark", { fg = c.accent })
    hi("NvimTreeLiveFilterPrefix", { fg = c.keyword, bold = true })
    hi("NvimTreeLiveFilterValue", { fg = c.string, bold = true })
    hi("NvimTreeWindowPicker", { fg = c.bg, bg = c.keyword, bold = true })

    -- [[ NEO-TREE ]] --

    hi("NeoTreeNormal", { fg = c.fg, bg = c.surface })
    hi("NeoTreeNormalNC", { fg = c.fg_muted, bg = c.surface })
    hi("NeoTreeRootName", { fg = c.accent, bold = true })
    hi("NeoTreeDirectoryName", { fg = c.func })
    hi("NeoTreeDirectoryIcon", { fg = c.info })
    hi("NeoTreeFileName", { fg = c.fg })
    hi("NeoTreeFileNameOpened", { fg = c.keyword })
    hi("NeoTreeSymbolicLinkTarget", { fg = c.type_ })
    hi("NeoTreeGitModified", { fg = c.warn })
    hi("NeoTreeGitAdded", { fg = c.ok })
    hi("NeoTreeGitDeleted", { fg = c.error })
    hi("NeoTreeGitConflict", { fg = c.error, bold = true })
    hi("NeoTreeGitStaged", { fg = c.ok })
    hi("NeoTreeGitUnstaged", { fg = c.warn })
    hi("NeoTreeGitUntracked", { fg = c.func })
    hi("NeoTreeWinSeparator", { fg = c.border, bg = c.surface })
    hi("NeoTreeIndentMarker", { fg = c.border })
    hi("NeoTreeExpander", { fg = c.operator })
    hi("NeoTreeFloatBorder", { fg = c.border, bg = c.float_bg })
    hi("NeoTreeFloatTitle", { fg = c.accent, bold = true })
    hi("NeoTreeCursorLine", { bg = c.bg_active })
    hi("NeoTreeStatusLine", { fg = c.surface, bg = c.surface })
    hi("NeoTreeTabActive", { fg = c.fg, bg = c.bg, bold = true })
    hi("NeoTreeTabInactive", { fg = c.fg_muted, bg = c.surface })
    hi("NeoTreeTabSeparatorActive", { fg = c.border_focus, bg = c.bg })
    hi("NeoTreeTabSeparatorInactive", { fg = c.border, bg = c.surface })
    hi("NeoTreeFilterTerm", { fg = c.string, bold = true })
    hi("NeoTreeDotfile", { fg = c.fg_subtle })
    hi("NeoTreeHiddenByName", { fg = c.fg_subtle })

    -- [[ GITSIGNS ]] --

    hi("GitSignsAdd", { fg = c.diff_add })
    hi("GitSignsChange", { fg = c.git_mod })
    hi("GitSignsDelete", { fg = c.diff_del })
    hi("GitSignsAddNr", { fg = c.diff_add })
    hi("GitSignsChangeNr", { fg = c.git_mod })
    hi("GitSignsDeleteNr", { fg = c.diff_del })
    hi("GitSignsAddLn", { bg = c.diff_add_bg })
    hi("GitSignsChangeLn", { bg = c.diff_chg_bg })
    hi("GitSignsDeleteLn", { bg = c.diff_del_bg })
    hi("GitSignsCurrentLineBlame", { fg = c.comment, italic = true })
    hi("GitSignsStagedAdd", { fg = c.ok })
    hi("GitSignsStagedChange", { fg = c.info })
    hi("GitSignsStagedDelete", { fg = c.error })
    hi("GitSignsAddPreview", { fg = c.diff_add, bg = c.diff_add_bg })
    hi("GitSignsDeletePreview", { fg = c.diff_del, bg = c.diff_del_bg })
    hi("GitSignsDeleteVirtLnum", { fg = c.diff_del })

    -- [[ INDENT-BLANKLINE ]] --

    hi("IblIndent", { fg = c.border })
    hi("IblScope", { fg = c.border_focus })
    hi("IblWhitespace", { fg = c.border })
    -- compat v2
    hi("IndentBlanklineChar", { fg = c.border })
    hi("IndentBlanklineContextChar", { fg = c.border_focus })
    hi("IndentBlanklineSpaceChar", { fg = c.border })
    hi("IndentBlanklineSpaceCharBlankline", { fg = c.border })

    -- [[ NVIM-CMP ]] --

    hi("CmpItemAbbr", { fg = c.fg })
    hi("CmpItemAbbrDeprecated", { fg = c.fg_muted, strikethrough = true })
    hi("CmpItemAbbrMatch", { fg = c.accent, bold = true })
    hi("CmpItemAbbrMatchFuzzy", { fg = c.accent })
    hi("CmpItemMenu", { fg = c.fg_muted, italic = true })
    hi("CmpItemKind", { fg = c.operator })
    hi("CmpItemKindText", { fg = c.fg_muted })
    hi("CmpItemKindMethod", { fg = c.func })
    hi("CmpItemKindFunction", { fg = c.func })
    hi("CmpItemKindConstructor", { fg = c.type_ })
    hi("CmpItemKindField", { fg = c.property })
    hi("CmpItemKindVariable", { fg = c.fg })
    hi("CmpItemKindClass", { fg = c.type_ })
    hi("CmpItemKindInterface", { fg = c.type_ })
    hi("CmpItemKindModule", { fg = c.namespace })
    hi("CmpItemKindProperty", { fg = c.property })
    hi("CmpItemKindUnit", { fg = c.number })
    hi("CmpItemKindValue", { fg = c.number })
    hi("CmpItemKindEnum", { fg = c.constant })
    hi("CmpItemKindKeyword", { fg = c.keyword })
    hi("CmpItemKindSnippet", { fg = c.string })
    hi("CmpItemKindColor", { fg = c.accent })
    hi("CmpItemKindFile", { fg = c.func })
    hi("CmpItemKindReference", { fg = c.property })
    hi("CmpItemKindFolder", { fg = c.func })
    hi("CmpItemKindEnumMember", { fg = c.constant })
    hi("CmpItemKindConstant", { fg = c.constant })
    hi("CmpItemKindStruct", { fg = c.type_ })
    hi("CmpItemKindEvent", { fg = c.property })
    hi("CmpItemKindOperator", { fg = c.operator })
    hi("CmpItemKindTypeParameter", { fg = c.type_ })
    hi("CmpDocumentation", { fg = c.fg, bg = c.float_bg })
    hi("CmpDocumentationBorder", { fg = c.float_border, bg = c.float_bg })
    hi("CmpGhostText", { fg = c.fg_disabled, italic = true })

    -- [[ BLINK-CMP ]] --

    hi("BlinkCmpMenu", { fg = c.fg, bg = c.float_bg })
    hi("BlinkCmpMenuBorder", { fg = c.float_border, bg = c.float_bg })
    hi("BlinkCmpMenuSelection", { fg = c.fg, bg = c.bg_active, bold = true })
    hi("BlinkCmpLabel", { fg = c.fg })
    hi("BlinkCmpLabelMatch", { fg = c.accent, bold = true })
    hi("BlinkCmpLabelDeprecated", { fg = c.fg_muted, strikethrough = true })
    hi("BlinkCmpLabelDetail", { fg = c.fg_muted, italic = true })
    hi("BlinkCmpLabelDescription", { fg = c.fg_muted, italic = true })
    hi("BlinkCmpKind", { fg = c.operator })
    hi("BlinkCmpKindText", { fg = c.fg_muted })
    hi("BlinkCmpKindMethod", { fg = c.func })
    hi("BlinkCmpKindFunction", { fg = c.func })
    hi("BlinkCmpKindConstructor", { fg = c.type_ })
    hi("BlinkCmpKindField", { fg = c.property })
    hi("BlinkCmpKindVariable", { fg = c.fg })
    hi("BlinkCmpKindClass", { fg = c.type_ })
    hi("BlinkCmpKindInterface", { fg = c.type_ })
    hi("BlinkCmpKindModule", { fg = c.namespace })
    hi("BlinkCmpKindProperty", { fg = c.property })
    hi("BlinkCmpKindUnit", { fg = c.number })
    hi("BlinkCmpKindValue", { fg = c.number })
    hi("BlinkCmpKindEnum", { fg = c.constant })
    hi("BlinkCmpKindKeyword", { fg = c.keyword })
    hi("BlinkCmpKindSnippet", { fg = c.string })
    hi("BlinkCmpKindColor", { fg = c.accent })
    hi("BlinkCmpKindFile", { fg = c.func })
    hi("BlinkCmpKindReference", { fg = c.property })
    hi("BlinkCmpKindFolder", { fg = c.func })
    hi("BlinkCmpKindEnumMember", { fg = c.constant })
    hi("BlinkCmpKindConstant", { fg = c.constant })
    hi("BlinkCmpKindStruct", { fg = c.type_ })
    hi("BlinkCmpKindEvent", { fg = c.property })
    hi("BlinkCmpKindOperator", { fg = c.operator })
    hi("BlinkCmpKindTypeParameter", { fg = c.type_ })
    hi("BlinkCmpDoc", { fg = c.fg, bg = c.float_bg })
    hi("BlinkCmpDocBorder", { fg = c.float_border, bg = c.float_bg })
    hi("BlinkCmpDocSeparator", { fg = c.border })
    hi("BlinkCmpGhostText", { fg = c.fg_disabled, italic = true })
    hi("BlinkCmpScrollBarThumb", { bg = c.border_focus })
    hi("BlinkCmpScrollBarGutter", { bg = c.bg_dark })
    hi("BlinkCmpSignatureHelp", { fg = c.fg, bg = c.float_bg })
    hi("BlinkCmpSignatureHelpBorder", { fg = c.float_border, bg = c.float_bg })
    hi("BlinkCmpSignatureHelpActiveParameter", { fg = c.warn, bold = true })

    -- [[ WHICH-KEY ]] --

    hi("WhichKey", { fg = c.keyword })
    hi("WhichKeyGroup", { fg = c.func })
    hi("WhichKeyDesc", { fg = c.fg })
    hi("WhichKeySeparator", { fg = c.comment })
    hi("WhichKeySeperator", { fg = c.comment })
    hi("WhichKeyFloat", { bg = c.float_bg })
    hi("WhichKeyBorder", { fg = c.border })
    hi("WhichKeyValue", { fg = c.fg_muted })
    hi("WhichKeyTitle", { fg = c.accent, bold = true })

    -- [[ NOICE + NOTIFY ]] --

    hi("NoiceCmdline", { fg = c.fg, bg = c.float_bg })
    hi("NoiceCmdlineIcon", { fg = c.accent })
    hi("NoiceCmdlineIconSearch", { fg = c.string })
    hi("NoiceCmdlinePopup", { fg = c.fg, bg = c.float_bg })
    hi("NoiceCmdlinePopupBorder", { fg = c.border, bg = c.float_bg })
    hi("NoiceCmdlinePopupTitle", { fg = c.accent })
    hi("NoicePopup", { fg = c.fg, bg = c.float_bg })
    hi("NoicePopupBorder", { fg = c.border, bg = c.float_bg })
    hi("NoiceConfirm", { fg = c.fg, bg = c.float_bg })
    hi("NoiceConfirmBorder", { fg = c.accent, bg = c.float_bg })
    hi("NoiceLspProgressSpinner", { fg = c.info })
    hi("NoiceLspProgressTitle", { fg = c.fg_muted })
    hi("NoiceLspProgressClient", { fg = c.func })
    hi("NoiceFormatProgressDone", { fg = c.bg, bg = c.ok })
    hi("NoiceFormatProgressTodo", { fg = c.fg_muted, bg = c.border })
    hi("NoiceScrollbar", { bg = c.bg_dark })
    hi("NoiceScrollbarThumb", { bg = c.border_focus })

    hi("NotifyBackground", { bg = c.float_bg })
    hi("NotifyERRORBorder", { fg = c.error })
    hi("NotifyWARNBorder", { fg = c.warn })
    hi("NotifyINFOBorder", { fg = c.info })
    hi("NotifyDEBUGBorder", { fg = c.comment })
    hi("NotifyTRACEBorder", { fg = c.operator })
    hi("NotifyERRORIcon", { fg = c.error })
    hi("NotifyWARNIcon", { fg = c.warn })
    hi("NotifyINFOIcon", { fg = c.info })
    hi("NotifyDEBUGIcon", { fg = c.fg_muted })
    hi("NotifyTRACEIcon", { fg = c.operator })
    hi("NotifyERRORTitle", { fg = c.error, bold = true })
    hi("NotifyWARNTitle", { fg = c.warn, bold = true })
    hi("NotifyINFOTitle", { fg = c.info, bold = true })
    hi("NotifyDEBUGTitle", { fg = c.fg_muted, bold = true })
    hi("NotifyTRACETitle", { fg = c.operator, bold = true })
    hi("NotifyERRORBody", { fg = c.fg, bg = c.float_bg })
    hi("NotifyWARNBody", { fg = c.fg, bg = c.float_bg })
    hi("NotifyINFOBody", { fg = c.fg, bg = c.float_bg })
    hi("NotifyDEBUGBody", { fg = c.fg, bg = c.float_bg })
    hi("NotifyTRACEBody", { fg = c.fg, bg = c.float_bg })

    -- [[ MINI.* ]] --

    hi("MiniStatuslineModeNormal", { fg = c.bg, bg = c.keyword, bold = true })
    hi("MiniStatuslineModeInsert", { fg = c.bg, bg = c.func, bold = true })
    hi("MiniStatuslineModeVisual", { fg = c.bg, bg = c.string, bold = true })
    hi("MiniStatuslineModeReplace", { fg = c.bg, bg = c.number, bold = true })
    hi("MiniStatuslineModeCommand", { fg = c.bg, bg = c.type_, bold = true })
    hi("MiniStatuslineModeOther", { fg = c.bg, bg = c.ok, bold = true })
    hi("MiniStatuslineFilename", { fg = c.fg, bg = c.bg_dark })
    hi("MiniStatuslineFileinfo", { fg = c.fg_muted, bg = c.bg_dark })
    hi("MiniStatuslineDevinfo", { fg = c.operator, bg = c.bg_dark })
    hi("MiniStatuslineInactive", { fg = c.fg_muted, bg = c.bg_dark })

    hi("MiniTablineCurrent", { fg = c.fg, bg = c.bg, bold = true })
    hi("MiniTablineVisible", { fg = c.fg, bg = c.surface })
    hi("MiniTablineHidden", { fg = c.fg_muted, bg = c.surface })
    hi("MiniTablineModifiedCurrent", { fg = c.string, bg = c.bg, bold = true })
    hi("MiniTablineModifiedVisible", { fg = c.string, bg = c.surface })
    hi("MiniTablineModifiedHidden", { fg = c.fg_muted, bg = c.surface })
    hi("MiniTablineFill", { bg = c.surface })

    hi("MiniCursorword", { underline = true })
    hi("MiniCursorwordCurrent", { underline = true })
    hi("MiniIndentscopeSymbol", { fg = c.border_focus })
    hi("MiniIndentscopePrefix", { nocombine = true })

    hi("MiniJump", { fg = c.bg, bg = c.string })
    hi("MiniJump2dSpot", { fg = c.string, bold = true, nocombine = true })
    hi("MiniJump2dSpotUnique", { fg = c.func, bold = true, nocombine = true })
    hi("MiniJump2dSpotAhead", { fg = c.fg_muted, nocombine = true })
    hi("MiniJump2dDim", { fg = c.fg_disabled })

    hi("MiniPickBorder", { fg = c.border, bg = c.float_bg })
    hi("MiniPickBorderBusy", { fg = c.warn, bg = c.float_bg })
    hi("MiniPickBorderText", { fg = c.accent, bg = c.float_bg })
    hi("MiniPickHeader", { fg = c.accent, bold = true })
    hi("MiniPickMatchCurrent", { bg = c.bg_active })
    hi("MiniPickMatchMarked", { bg = c.diff_chg_bg })
    hi("MiniPickMatchRanges", { fg = c.accent, bold = true })
    hi("MiniPickNormal", { fg = c.fg, bg = c.float_bg })
    hi("MiniPickPrompt", { fg = c.func, bg = c.float_bg })

    hi("MiniDiffSignAdd", { fg = c.diff_add })
    hi("MiniDiffSignChange", { fg = c.diff_chg })
    hi("MiniDiffSignDelete", { fg = c.diff_del })
    hi("MiniDiffOverAdd", { bg = c.diff_add_bg })
    hi("MiniDiffOverChange", { bg = c.diff_chg_bg })
    hi("MiniDiffOverDelete", { bg = c.diff_del_bg })
    hi("MiniDiffOverContext", { bg = c.surface })

    hi("MiniNotifyBorder", { fg = c.float_border, bg = c.float_bg })
    hi("MiniNotifyNormal", { fg = c.fg, bg = c.float_bg })
    hi("MiniNotifyTitle", { fg = c.accent, bold = true })

    hi("MiniFilesNormal", { fg = c.fg, bg = c.float_bg })
    hi("MiniFilesBorder", { fg = c.float_border, bg = c.float_bg })
    hi("MiniFilesTitle", { fg = c.accent, bold = true })
    hi("MiniFilesTitleFocused", { fg = c.accent, bg = c.float_bg, bold = true })
    hi("MiniFilesCursorLine", { bg = c.bg_active })
    hi("MiniFilesDirectory", { fg = c.func })

    hi("MiniMapNormal", { fg = c.fg_muted, bg = c.surface })
    hi("MiniMapSymbolCount", { fg = c.number })
    hi("MiniMapSymbolLine", { fg = c.accent })
    hi("MiniMapSymbolView", { fg = c.border_focus })

    hi("MiniStarterCurrent", { fg = c.fg, bold = true })
    hi("MiniStarterFooter", { fg = c.comment, italic = true })
    hi("MiniStarterHeader", { fg = c.accent, bold = true })
    hi("MiniStarterInactive", { fg = c.fg_disabled })
    hi("MiniStarterItem", { fg = c.fg })
    hi("MiniStarterItemBullet", { fg = c.border })
    hi("MiniStarterItemPrefix", { fg = c.keyword })
    hi("MiniStarterQuery", { fg = c.string })
    hi("MiniStarterSection", { fg = c.func, bold = true })

    hi("MiniHipatternsFixme", { fg = c.bg, bg = c.error, bold = true })
    hi("MiniHipatternsHack", { fg = c.bg, bg = c.warn, bold = true })
    hi("MiniHipatternsTodo", { fg = c.bg, bg = c.keyword, bold = true })
    hi("MiniHipatternsNote", { fg = c.bg, bg = c.info, bold = true })

    hi("MiniClueNextKey", { fg = c.keyword, bold = true })
    hi("MiniClueNextKeyWithPostkeys", { fg = c.type_, bold = true })
    hi("MiniClueSeparator", { fg = c.comment })
    hi("MiniClueDescGroup", { fg = c.func })
    hi("MiniClueDescSingle", { fg = c.fg })
    hi("MiniClueTitle", { fg = c.accent, bold = true })
    hi("MiniClueBorder", { fg = c.border })

    -- [[ FLASH.NVIM ]] --

    hi("FlashBackdrop", { fg = c.fg_muted })
    hi("FlashLabel", { fg = c.bg, bg = c.string, bold = true })
    hi("FlashMatch", { fg = c.bg, bg = c.keyword })
    hi("FlashCurrent", { fg = c.bg, bg = c.type_ })
    hi("FlashPrompt", { fg = c.accent })
    hi("FlashPromptIcon", { fg = c.string })
    hi("FlashCursor", { fg = c.bg, bg = c.accent })

    -- [[ LAZY.NVIM ]] --

    hi("LazyNormal", { fg = c.fg, bg = c.float_bg })
    hi("LazyBorder", { fg = c.border, bg = c.float_bg })
    hi("LazyButton", { fg = c.fg, bg = c.bg_active })
    hi("LazyButtonActive", { fg = c.bg, bg = c.keyword, bold = true })
    hi("LazyH1", { fg = c.keyword, bold = true })
    hi("LazyH2", { fg = c.func, bold = true })
    hi("LazyReasonPlugin", { fg = c.func })
    hi("LazyReasonSource", { fg = c.type_ })
    hi("LazyReasonRuntime", { fg = c.string })
    hi("LazyReasonEvent", { fg = c.number })
    hi("LazyReasonKeys", { fg = c.keyword })
    hi("LazyReasonStart", { fg = c.ok })
    hi("LazyProgressTodo", { fg = c.border })
    hi("LazyProgressDone", { fg = c.ok })
    hi("LazySpecial", { fg = c.string })
    hi("LazyDir", { fg = c.func })
    hi("LazyUrl", { fg = c.func, underline = true })
    hi("LazyCommit", { fg = c.number })
    hi("LazyCommitIssue", { fg = c.type_ })
    hi("LazyCommitType", { fg = c.keyword })
    hi("LazyCommitScope", { fg = c.func })
    hi("LazyTaskOutput", { fg = c.fg_muted })
    hi("LazyDimmed", { fg = c.fg_disabled })
    hi("LazyProp", { fg = c.fg_muted })
    hi("LazyValue", { fg = c.string })
    hi("LazyLocal", { fg = c.ok })
    hi("LazyNoCond", { fg = c.warn })

    -- [[ MASON.NVIM ]] --

    hi("MasonNormal", { fg = c.fg, bg = c.float_bg })
    hi("MasonHeader", { fg = c.bg, bg = c.keyword, bold = true })
    hi("MasonHighlight", { fg = c.keyword })
    hi("MasonHighlightBlock", { fg = c.bg, bg = c.keyword })
    hi("MasonHighlightBlockBold", { fg = c.bg, bg = c.keyword, bold = true })
    hi("MasonMuted", { fg = c.fg_muted })
    hi("MasonMutedBlock", { fg = c.fg, bg = c.bg_active })
    hi("MasonError", { fg = c.error })
    hi("MasonWarning", { fg = c.warn })
    hi("MasonHeading", { fg = c.keyword, bold = true })
    hi("MasonLink", { fg = c.func, underline = true })

    -- [[ TROUBLE.NVIM ]] --

    hi("TroubleNormal", { fg = c.fg, bg = c.surface })
    hi("TroubleNormalNC", { fg = c.fg_muted, bg = c.surface })
    hi("TroubleCount", { fg = c.number, bold = true })
    hi("TroubleCode", { fg = c.string })
    hi("TroubleFile", { fg = c.func })
    hi("TroubleFolderIcon", { fg = c.info })
    hi("TroubleIconError", { fg = c.error })
    hi("TroubleIconWarning", { fg = c.warn })
    hi("TroubleIconInformation", { fg = c.info })
    hi("TroubleIconHint", { fg = c.hint })
    hi("TroubleIconOther", { fg = c.fg_muted })
    hi("TroubleText", { fg = c.fg })
    hi("TroubleTextError", { fg = c.error })
    hi("TroubleTextWarning", { fg = c.warn })
    hi("TroubleTextInformation", { fg = c.info })
    hi("TroubleTextHint", { fg = c.hint })
    hi("TroubleLocation", { fg = c.fg_muted })
    hi("TroubleSource", { fg = c.comment })
    hi("TroublePreview", { bg = c.bg_active })
    hi("TroubleIndent", { fg = c.border })
    hi("TroublePos", { fg = c.comment })

    -- [[ AERIAL.NVIM ]] --

    hi("AerialNormal", { fg = c.fg, bg = c.surface })
    hi("AerialNormalNC", { fg = c.fg_muted, bg = c.surface })
    hi("AerialLine", { bg = c.bg_active })
    hi("AerialLineNC", { bg = c.bg_active })
    hi("AerialGuide", { fg = c.border })
    hi("AerialClass", { fg = c.type_ })
    hi("AerialClassIcon", { fg = c.type_ })
    hi("AerialFunction", { fg = c.func })
    hi("AerialFunctionIcon", { fg = c.func })
    hi("AerialConstructor", { fg = c.type_ })
    hi("AerialInterface", { fg = c.type_ })
    hi("AerialModule", { fg = c.namespace })
    hi("AerialMethod", { fg = c.func })
    hi("AerialProperty", { fg = c.property })
    hi("AerialField", { fg = c.property })
    hi("AerialEnum", { fg = c.constant })
    hi("AerialEnumMember", { fg = c.constant })
    hi("AerialStruct", { fg = c.type_ })
    hi("AerialVariable", { fg = c.fg })
    hi("AerialConstant", { fg = c.constant })
    hi("AerialKey", { fg = c.keyword })
    hi("AerialOperator", { fg = c.operator })

    -- [[ ALPHA / DASHBOARD ]] --

    hi("AlphaHeader", { fg = c.accent, bold = true })
    hi("AlphaHeaderLabel", { fg = c.keyword })
    hi("AlphaButtons", { fg = c.func })
    hi("AlphaShortcut", { fg = c.number })
    hi("AlphaFooter", { fg = c.comment, italic = true })

    hi("DashboardHeader", { fg = c.accent, bold = true })
    hi("DashboardCenter", { fg = c.func })
    hi("DashboardShortcut", { fg = c.number })
    hi("DashboardFooter", { fg = c.comment, italic = true })
    hi("DashboardKey", { fg = c.keyword })
    hi("DashboardDesc", { fg = c.fg })
    hi("DashboardIcon", { fg = c.info })

    -- [[ SNACKS.NVIM ]] --

    hi("SnacksNormal", { fg = c.fg, bg = c.float_bg })
    hi("SnacksNormalNC", { fg = c.fg_muted, bg = c.float_bg })
    hi("SnacksBorder", { fg = c.float_border, bg = c.float_bg })
    hi("SnacksTitle", { fg = c.accent, bold = true })
    hi("SnacksFooter", { fg = c.fg_muted, bg = c.float_bg })
    hi("SnacksCursor", { fg = c.bg, bg = c.accent })
    hi("SnacksInputNormal", { fg = c.fg, bg = c.float_bg })
    hi("SnacksInputBorder", { fg = c.border_focus, bg = c.float_bg })
    hi("SnacksInputTitle", { fg = c.accent, bold = true })
    hi("SnacksPickerDir", { fg = c.fg_muted })
    hi("SnacksPickerFile", { fg = c.fg })
    hi("SnacksPickerGitStatusAdded", { fg = c.diff_add })
    hi("SnacksPickerGitStatusModified", { fg = c.diff_chg })
    hi("SnacksPickerGitStatusDeleted", { fg = c.diff_del })
    hi("SnacksPickerMatch", { fg = c.accent, bold = true })
    hi("SnacksPickerSelected", { fg = c.type_, bg = c.bg_active })
    hi("SnacksScratchKey", { fg = c.keyword, bold = true })
    hi("SnacksScratchDesc", { fg = c.fg_muted })
    hi("SnacksDashboardHeader", { fg = c.accent, bold = true })
    hi("SnacksDashboardFooter", { fg = c.comment, italic = true })
    hi("SnacksDashboardDesc", { fg = c.fg })
    hi("SnacksDashboardIcon", { fg = c.info })
    hi("SnacksDashboardKey", { fg = c.keyword })
    hi("SnacksDashboardTerminal", { fg = c.fg, bg = c.bg })
    hi("SnacksDashboardSpecial", { fg = c.accent })
    hi("SnacksNotifierBorderError", { fg = c.error })
    hi("SnacksNotifierBorderWarn", { fg = c.warn })
    hi("SnacksNotifierBorderInfo", { fg = c.info })
    hi("SnacksNotifierBorderDebug", { fg = c.comment })
    hi("SnacksNotifierBorderTrace", { fg = c.operator })
    hi("SnacksNotifierIconError", { fg = c.error })
    hi("SnacksNotifierIconWarn", { fg = c.warn })
    hi("SnacksNotifierIconInfo", { fg = c.info })
    hi("SnacksNotifierIconDebug", { fg = c.fg_muted })
    hi("SnacksNotifierIconTrace", { fg = c.operator })
    hi("SnacksNotifierTitleError", { fg = c.error, bold = true })
    hi("SnacksNotifierTitleWarn", { fg = c.warn, bold = true })
    hi("SnacksNotifierTitleInfo", { fg = c.info, bold = true })
    hi("SnacksNotifierTitleDebug", { fg = c.fg_muted, bold = true })
    hi("SnacksNotifierTitleTrace", { fg = c.operator, bold = true })

    -- [[ BUFFERLINE.NVIM ]] --

    hi("BufferLineFill", { bg = c.bg_dark })
    hi("BufferLineBackground", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineBufferVisible", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineBufferSelected", { fg = c.fg, bg = c.bg, bold = true })
    hi("BufferLineTab", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineTabSelected", { fg = c.fg, bg = c.bg, bold = true })
    hi("BufferLineTabClose", { fg = c.error, bg = c.surface })
    hi("BufferLineTabSeparator", { fg = c.border, bg = c.surface })
    hi("BufferLineTabSeparatorSelected", { fg = c.border_focus, bg = c.bg })
    hi("BufferLineSeparator", { fg = c.border, bg = c.surface })
    hi("BufferLineSeparatorVisible", { fg = c.border, bg = c.surface })
    hi("BufferLineSeparatorSelected", { fg = c.border_focus, bg = c.bg })
    hi("BufferLineIndicatorSelected", { fg = c.accent, bg = c.bg })
    hi("BufferLineIndicatorVisible", { fg = c.surface, bg = c.surface })
    hi("BufferLineCloseButton", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineCloseButtonVisible", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineCloseButtonSelected", { fg = c.error, bg = c.bg })
    hi("BufferLineModified", { fg = c.string, bg = c.surface })
    hi("BufferLineModifiedVisible", { fg = c.string, bg = c.surface })
    hi("BufferLineModifiedSelected", { fg = c.string, bg = c.bg })
    hi("BufferLinePinned", { fg = c.keyword, bg = c.surface })
    hi("BufferLinePinnedVisible", { fg = c.keyword, bg = c.surface })
    hi("BufferLinePinnedSelected", { fg = c.keyword, bg = c.bg })
    hi("BufferLineError", { fg = c.error, bg = c.surface })
    hi("BufferLineErrorVisible", { fg = c.error, bg = c.surface })
    hi("BufferLineErrorSelected", { fg = c.error, bg = c.bg })
    hi("BufferLineWarning", { fg = c.warn, bg = c.surface })
    hi("BufferLineWarningVisible", { fg = c.warn, bg = c.surface })
    hi("BufferLineWarningSelected", { fg = c.warn, bg = c.bg })
    hi("BufferLineInfo", { fg = c.info, bg = c.surface })
    hi("BufferLineInfoVisible", { fg = c.info, bg = c.surface })
    hi("BufferLineInfoSelected", { fg = c.info, bg = c.bg })
    hi("BufferLineHint", { fg = c.hint, bg = c.surface })
    hi("BufferLineHintVisible", { fg = c.hint, bg = c.surface })
    hi("BufferLineHintSelected", { fg = c.hint, bg = c.bg })
    hi("BufferLineNumbers", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineNumbersVisible", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineNumbersSelected", { fg = c.fg, bg = c.bg, bold = true })
    hi("BufferLineTruncationMarker", { fg = c.fg_muted, bg = c.surface })
    hi("BufferLineGroupLabel", { fg = c.bg, bg = c.keyword, bold = true })
    hi("BufferLineGroupSeparator", { fg = c.border })
    hi("BufferLineOffsetSeparator", { fg = c.border, bg = c.surface })

    -- [[ LUALINE (via link) ]] --
    -- lualine defines its own groups; these links ensure
    -- that themes without explicit lualine config inherit the correct colors.

    hi("lualine_a_normal", { fg = c.bg, bg = c.keyword, bold = true })
    hi("lualine_a_insert", { fg = c.bg, bg = c.func, bold = true })
    hi("lualine_a_visual", { fg = c.bg, bg = c.string, bold = true })
    hi("lualine_a_replace", { fg = c.bg, bg = c.number, bold = true })
    hi("lualine_a_command", { fg = c.bg, bg = c.type_, bold = true })
    hi("lualine_a_inactive", { fg = c.fg_muted, bg = c.bg_dark })
    hi("lualine_b_normal", { fg = c.fg, bg = c.bg_dark })
    hi("lualine_b_insert", { fg = c.fg, bg = c.bg_dark })
    hi("lualine_b_visual", { fg = c.fg, bg = c.bg_dark })
    hi("lualine_b_replace", { fg = c.fg, bg = c.bg_dark })
    hi("lualine_b_command", { fg = c.fg, bg = c.bg_dark })
    hi("lualine_b_inactive", { fg = c.fg_muted, bg = c.bg_dark })
    hi("lualine_c_normal", { fg = c.fg_muted, bg = c.bg_dark })
    hi("lualine_c_inactive", { fg = c.fg_disabled, bg = c.bg_dark })

    -- [[ RENDER-MARKDOWN.NVIM ]] --

    hi("RenderMarkdownH1", { fg = c.keyword, bold = true })
    hi("RenderMarkdownH2", { fg = c.type_, bold = true })
    hi("RenderMarkdownH3", { fg = c.func, bold = true })
    hi("RenderMarkdownH4", { fg = c.string, bold = true })
    hi("RenderMarkdownH5", { fg = c.number, bold = true })
    hi("RenderMarkdownH6", { fg = c.operator, bold = true })
    hi("RenderMarkdownH1Bg", { bg = c.bg_active })
    hi("RenderMarkdownH2Bg", { bg = c.bg_active })
    hi("RenderMarkdownH3Bg", { bg = c.bg_active })
    hi("RenderMarkdownCode", { bg = c.surface })
    hi("RenderMarkdownCodeInline", { fg = c.string, bg = c.surface })
    hi("RenderMarkdownBullet", { fg = c.accent })
    hi("RenderMarkdownQuote", { fg = c.comment })
    hi("RenderMarkdownDash", { fg = c.border })
    hi("RenderMarkdownLink", { fg = c.func, underline = true })
    hi("RenderMarkdownMath", { fg = c.number })
    hi("RenderMarkdownSign", { fg = c.info })
    hi("RenderMarkdownChecked", { fg = c.ok })
    hi("RenderMarkdownUnchecked", { fg = c.fg_muted })
    hi("RenderMarkdownTodo", { fg = c.bg, bg = c.keyword, bold = true })
    hi("RenderMarkdownTableHead", { fg = c.keyword, bold = true })
    hi("RenderMarkdownTableRow", { fg = c.fg })
    hi("RenderMarkdownTableFill", { fg = c.border })

    -- [[ TERMINAL COLORS ]] --

    vim.g.terminal_color_0  = c.bg
    vim.g.terminal_color_1  = c.error
    vim.g.terminal_color_2  = c.ok
    vim.g.terminal_color_3  = c.warn
    vim.g.terminal_color_4  = c.func
    vim.g.terminal_color_5  = c.keyword
    vim.g.terminal_color_6  = c.type_
    vim.g.terminal_color_7  = c.fg
    vim.g.terminal_color_8  = c.comment
    vim.g.terminal_color_9  = c.error
    vim.g.terminal_color_10 = c.ok
    vim.g.terminal_color_11 = c.number
    vim.g.terminal_color_12 = c.func
    vim.g.terminal_color_13 = c.string
    vim.g.terminal_color_14 = c.type_
    vim.g.terminal_color_15 = c.term_bw

    -- Paletas com tabela ANSI customizada (ex: cinder) sobrescrevem via overrides
    if type(c.t) == "table" then
        local t = c.t
        if t.black        then vim.g.terminal_color_0  = t.black        end
        if t.red          then vim.g.terminal_color_1  = t.red          end
        if t.green        then vim.g.terminal_color_2  = t.green        end
        if t.yellow       then vim.g.terminal_color_3  = t.yellow       end
        if t.blue         then vim.g.terminal_color_4  = t.blue         end
        if t.magenta      then vim.g.terminal_color_5  = t.magenta      end
        if t.cyan         then vim.g.terminal_color_6  = t.cyan         end
        if t.white        then vim.g.terminal_color_7  = t.white        end
        if t.black_br     then vim.g.terminal_color_8  = t.black_br     end
        if t.red_br       then vim.g.terminal_color_9  = t.red_br       end
        if t.green_br     then vim.g.terminal_color_10 = t.green_br     end
        if t.yellow_br    then vim.g.terminal_color_11 = t.yellow_br    end
        if t.blue_br      then vim.g.terminal_color_12 = t.blue_br      end
        if t.magenta_br   then vim.g.terminal_color_13 = t.magenta_br   end
        if t.cyan_br      then vim.g.terminal_color_14 = t.cyan_br      end
        if t.white_br     then vim.g.terminal_color_15 = t.white_br     end
    end
end

return M
